language: python

python:
    - 2.7
    - 3.5
    - 3.6
install: 
  - pip install -r requirements.txt
  - pip install codecov

before_script:
  - psql -c 'create database app;' -U postgres
  - psql -c 'create database test;' -U postgres
  - psql -c "create user app_user WITH PASSWORD 'app_user_pass';" -U postgres
script:
  - coverage erase
  - coverage run tests.py && coverage html
after_success:
  - codecov

deploy:
   - provider: heroku
     api_key:
        secure: L7eJS1plFtwawjmCglN/c3O7XOOOJgge3O51TeL25PHwXAhdMkD7FgWQIQYHo5AmgMNgwjvQXoObBYnJ4yJSFi94UAAFj5x4/DT12t4kX15/PEbwMkkTNcHXkJEblTPIlkAzv1nuOm3meBDlAjPb4QyHAXHlpKVp/Hj10Z4E9cY/khRAqI//c9q9DimNqhTctuYrFJ4BBWLOLuA4oqQ6zVhhsJAG0bVRMArYAjVvRQU1/pXY/0EH8vA8lfNVV+gHkoHdpxXTboeVxPnPq2XfM4hTHUY7j7A4HVbHSb2nsrJh8kFqq3wvwuG2mW/EzsYnqq0F/JhiH3ctyv986MkfUKhAWifhN0re1cg91wujuz4mnevJ+rzTUn6/SHCdyaam4IuTrh5lejLy5s/66vRxngNBSNKtMG0pvVLauc3/r6fxm6bGhUoxOelYbDTj85ecpdDJx+TSFs/FFyDlmNzklJ1KOtZFFrjNcINIwTJ1Lhj2bF1X6Rt3sS8vEH+VtGZIpAMi064eo9TGO4IIQNnh/zO9Gas7Wrhxh9agSnRgLq/lX6a+kMu1mQp0mhglp4qwdgzqjK8IRF87hPYv56yuvmLT0djnId3ImmyeKC5rqOSIddaQECf7DH/VA4f3swIVXtUNZz6zDklS/sxNmbtbMf/rzIIsj6ysRpdGbxCkdto=
     app: obscure-mountain-29302

