language: python

python:
    - 2.7
install: 
  - pip install -r requirements.txt
  - pip install codecov
script:
  - coverage erase
  - coverage run tests.py && coverage html
#  - pylint --output-format=text webapp.py
after_success:
  - codecov
  

deploy:
   provider: s3
   access_key_id: AKIAJENN2CP5WCB32EZQ
   secret_access_key: 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
   bucket: engineeringproject
