language: python

python:
    - "2.7"
    - "3.5"
    - "3.6"
install: 
  - pip install -r requirements.txt
  - pip install codecov
script:
  - coverage erase
  - coverage run app/tests.py && coverage html
#  - pylint --output-format=text webapp.py
after_success:
  - codecov
